seq_1 <- readDNAStringSet("/Users/Alvin/Downloads/sequence (1).fasta")
seqs <- c(seq_1, seq_2, seq_3, seq_4, seq_5)
names(seqs)
names(seqs) <- c("BV354391.1 Rottweiler", "KY994015.1 Galeocerdo", "CG891703.1 Yunnan","LZ248448.1 Functional Influenza", "FJ712034.1 Panthera")
Alv <- msa(seqs)
nchar(Alv)
print(Alv, show="complete")
alFreq <- alphabetFrequency(Alv)
alFreq
sum(alFreq[,"C"]) + sum(alFreq[,"G"]) 
sum(alFreq[,"A"]) + sum(alFreq[,"T"]) 
GC / (GC + AT )
seq_1.seqinr <- seqinr::read.fasta("/Users/Alvin/Downloads/sequence (1).fasta")
seqinr::GC(seq_1.seqinr$BV354391.1)
Alvx <- msaConvert(Alv, type="seqinr::alignment")
d <- dist.alignment(Alvx, "identity")
100 - (round(as.matrix(d)["BV354391.1", drop=FALSE], digits = 2) * 100)
Alv_phyDat <- msaConvert(Alv, type="phangorn::phyDat")
write.fasta("Alvx", "Alvx", "Alv.fasta")
